Broken version after refactoring.
RAMTabBar implemented. Refactored to multiple storyboards

Error message...

fatal error: items must inherit RAMAnimatedTabBarItem: file ../TestingAnimatedTabBar/Pods/RAMAnimatedTabBarController/RAMAnimatedTabBarController/RAMAnimatedTabBarController.swift, line 155
(lldb)